---
- name: "Pull and run docker image with community.docker on localhost"
  hosts: "localhost"
  vars_files:
    - /run/provisioning/ansible_vars.yaml
  tasks:
    - name: "Pull and run image"
      become: "true"
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        pull: "always"
        restart_policy: "unless-stopped"
        state: "started"
        published_ports: "{{ ports }}"
        env_file: "{{ env_file }}"
