---
- name: "Pull and run docker image with community.docker on localhost"
  hosts: "localhost"
  tasks:
    - name: "Pull and run image"
      become: "true"
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        pull: "true"
        restart_policy: "unless-stopped"
        state: "started"
        published_ports: "{{ ports }}"
        env:
            DB_TYPE: "{{ db_type }}"
            DB_NAME: "{{ db_name }}"
            DB_HOST: "{{ db_host }}"
            DB_PORT: "{{ db_port }}"
            DB_USER: "{{ db_user }}"
            DB_PASS: "{{ db_pass }}"
